version: "3.8"

services:
  backend:
    build: ./backend
    container_name: mino-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: mino-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
        - backend
